/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuanyantech_seecool_ndk_DataProvider */

#ifndef _Included_com_huotu_mall_wenslimall_partnermall_ndk_DataProvider
#define _Included_com_huotu_mall_wenslimall_partnermall_ndk_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
void getGiftPath(const char *path);

void photoSucceed(const char *photoPath);

void videoRerurnEvent();
#ifdef __cplusplus
}


#endif
#endif
